apiVersion: v1
kind: Namespace
metadata:
  name: "xmrig"
  labels:
    name: "xmrig"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xmrig
  namespace: xmrig
  labels:
    app: xmrig  
spec:
  selector:
      matchLabels:
        app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      # tolerations:
      # # This toleration is to have the daemonset runnable on master nodes
      # # uncomment this section if your masters can run pods
      # - key: node-role.kubernetes.io/master
      #   effect: NoSchedule
      containers:
        - name: xmrig-cpu
          image: "zetneteork/xmrig:latest"
          # --run-as UID should match runAsUser value in containers securityContext
          command:
            - "/xmrig/xmrig"
          resources:
            #limits:
            #  cpu: 1000m # How much CPU you wish to donate per node
            #  memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          # Make the container harder to break out of or exploit
          securityContext:
            #runAsNonRoot: true
            #runAsUser: 1234
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
---